### ISSUE TITLE
How to read streams

### ISSUE THREAD

**Issue by SteffenBrinckmann** [decalage2/olefile#129]
Hey,
I have an ole-file, which is from a vendors VC++ 9.0 software. I can list the directories (ole.listdir) and get the stream size from an ole-file. But how to decode the streams themselves? I guess they are double or int arrays, but find no ability to decode them.
I tried all byte-order encodings and struct.unpack sizes, with no hope insight. 

Any help / suggestions would be appreciated. 
Thank you, 
Steffen
P.S. the ole-file is 0.75MB.

**Comment by decalage2** [comment]
Hi Steffen, I am not sure what you are asking: 
Streams are just like binary files within the OLE file. You can open them with the openstream method, and then read data using read() like with any normal file on disk. See https://olefile.readthedocs.io/en/latest/Howto.html#read-data-from-a-stream
What you get is bytes, then how to interpret those bytes depends on the application which created the file, it can be anything.

**Comment by SteffenBrinckmann** [comment]
Dear Decalage2,
Yes, I was asking on how to decipher the data-stream bytes. I understand it can be anything. 
I thought there should be a method in identifying the anything given that some things are known (numbers stored as double, float, int). It computer science there are mostly a fixed set of well established methods, and one could try all those established methods.
Thanks,

**Comment by decalage2** [comment]
Unfortunately this is usually much more complicated than that, you do need to have a documentation explaining how to parse the binary data of the specific stream you want to decode. If you look at Microsoft documentation for their file formats, it can be extremely complex to parse (e.g Word files), and completely different for each file format.
