### ISSUE TITLE
question: does olefile support password protected files?

### ISSUE THREAD

**Issue by benzkji** [decalage2/olefile#139]
just wondering...? a quick search in docs doesnt show a thing...

**Comment by decalage2** [comment]
This is a good question and indeed it is not mentioned in the documentation. 
Actually there is no encryption at the OLE / compound file container level. When encryption is used by an application such as MS Office to protect data in a file, it is always done at the application level.
An OLE file is just a container, that can store data organised in streams and storages. It's up to the application to manage the data (and potentially encryption).
So olefile does not manage encryption by itself.
For example if you need to decrypt/encrypt data in MS Office files, there are other libraries such as [msoffcrypto-tool](https://github.com/nolze/msoffcrypto-tool) that can handle it on top of olefile. I use it in [oletools](https://github.com/decalage2/oletools).

- [ ] TODO: add this explanation to the documentation
