### ISSUE TITLE
Any plans to make new the release?

### ISSUE THREAD

**Issue by kloczek** [decalage2/olefile#147]
I see +60 commits in git repo since last release.
Do you have any plans to flush those commits as new the release? 😄

**Comment by christian-intra2net** [comment]
I would appreciate a release as well. I just spent 2 hours hunting down an error that occurred in oletools tests just to find that it is fixed in olefile already, just not contained in any release rpms out there.

**Comment by decalage2** [comment]
Indeed it's a long-awaited release. I'll see if I can do it in the near future.

**Comment by hugovk** [comment]
This can be closed, 0.47 was released in December 🚀 

https://pypi.org/project/olefile/0.47/

**Comment by kloczek** [comment]
Yep. Closing.
Thank you 👍
