### ISSUE TITLE
mail format

### ISSUE THREAD

**Issue by bphd** [decalage2/olefile#148]
Do you know what format use Microsoft to store its mails in OST/PST files? HTML/EML/MESSAGE/etc.

**Comment by decalage2** [comment]
It's a specific format, not sure it's related to olefile:
https://docs.fileformat.com/email/pst/
https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-pst/141923d5-15ab-4ef1-a524-6dce75aae546
