### ISSUE TITLE
"Say Thanks" button in readme leads to "Not Found" page.

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [decalage2/olefile#161]
As the title says, the button does not appear to function as intended as it leads to a "not found" page.

If you're already aware of this, you can just ignore this issue.

**Comment by decalage2** [comment]
Thanks for reporting it! You must be the first person clicking on the button since I added it several years ago... 😂

**Comment by decalage2** [comment]
I reactivated my account, and now it should work again.
