### ISSUE TITLE
Incorrect file encodings and unnecessary shebangs

### ISSUE THREAD

**Issue by manisandro** [decalage2/olefile#50]
The following issues were pointed out during the fedora package review:
- The python modules don't need a shebang, since they are not intended to be used as standalone scripts:

      sed -i -e '1{\@^#!/usr/local/bin/python@d}' OleFileIO_PL.py
      sed -i -e '1{\@^#!/usr/local/bin/python@d}' olefile/__init__.py
      sed -i -e '1{\@^#!/usr/bin/env python@d}' olefile/olefile.py

- There are some incorrect file endings:

      sed -i -e "s/\r//" olefile/doc/*.md
      sed -i -e "s/\r//" OleFileIO_PL.py

Furthermore I don't think that it is good practice to install the documentation files underneath the `site-packages` directory, they rather belong underneath `/usr/share/doc`, depending on distro policy, so I think they simply should not get installed through `setup.py install` but left for the packager to handle.

**Comment by decalage2** [comment]
Hi @manisandro, thank you for reporting those issues.

olefile is actually meant to be used both as a python module and a command line script, mainly for debugging or to check an OLE file. But you're right for the other two files, I'll fix it.

For the file endings, what is the actual issue?

As for the doc subfolder, I did not find a proper way to install documentation files with the python code using pip, working on all OS platforms. Relying on distributions and /usr/share/doc would only work for Linux. I am currently migrating the doc to Sphinx + readthedocs, so maybe I'll just get rid of the doc subfolder.

**Comment by manisandro** [comment]
Ah yes missed the __main__ part in `olefile.py`. However perhaps it would be an idea to move the script part to a separate file which imports olefile? Typically one does not install executable scripts to site-packages.

Line endings: https://fedoraproject.org/wiki/Common_Rpmlint_issues#wrong-script-end-of-line-encoding

And sphinx for docs would be great!

**Comment by decalage2** [comment]
I think all the issues you reported are now fixed on the repository version. I'll close the ticket once v0.44 is released on PyPI, and if you confirm it works on your side.

**Comment by manisandro** [comment]
Thanks! Any opinion on splitting off the `__main__` routine in `olefile.py` to a separate script?

**Comment by decalage2** [comment]
I prefer to keep the small main script in olefile, to keep things simple. But I will simply remove the shebang line: after all it is not required when running "python olefile.py". If that's easier for distributions, let's do it.

**Comment by manisandro** [comment]
Thanks (the background is that rpmlint flags it as an error if a script with shebang is not executable).

**Comment by decalage2** [comment]
I just uploaded olefile 0.44 to PyPI, it should now work fine. 

https://pypi.python.org/pypi/olefile
