### ISSUE TITLE
Please distribute tests folder in PyPi release and/or tag releases in git

### ISSUE THREAD

**Issue by manisandro** [decalage2/olefile#56]
Since the PyPi release is currently the most practical release to work with for packaging in distros, it would be great if it also included the tests folder.
Or it would also help if releases were tagged in git, so that one can pull the source directly from github but still keep in human readable (i.e. 0.44 vs 729bbef31eaabcdfeb7987f4fb70d21fcc897bc6). Git tags would also help packagers understand which git revision actually corresponds to a release version.

**Comment by hugovk** [comment]
It may be useful to include a RELEASING.md checklist.

See for example:
* https://github.com/python-pillow/Pillow/blob/master/RELEASING.md
* https://github.com/pylast/pylast/blob/develop/RELEASING.md

**Comment by decalage2** [comment]
@manisandro, I just created a tag and release for v0.44. Do you also need me to include the tests folder into the future releases?

**Comment by manisandro** [comment]
As far as I'm concerned the tag is sufficient to be able to generate a complete source tarball.

Generally speaking though it would be best to have the official source archive as complete as possible. Indeed, the best thing would be if

https://github.com/decalage2/olefile/releases/download/v0.44/olefile-0.44.zip

was actually identical to the PyPi release, as to not have diverging source tarballs depending on where one downloaded it from.

**Comment by decalage2** [comment]
OK. I just checked olefile-0.44.zip, it is the same file on PyPI and GitHub.

I'll include the tests folder in the next release 0.45.

**Comment by decalage2** [comment]
fixed in commit 2a7fd61b57a9d234034f3fb7f90a8b8ac1aa5bca
