### ISSUE TITLE
missing module exports

### ISSUE THREAD

**Issue by jerzyk** [decalage2/olefile#79]
method `__init__` of class `OleFileIO` is using constants in parameter declarations, but those constants are not exported in `__all__`, of course they could be redefined in the module that is implementing a class inheriting from `OleFileIO`... but it is breaking DRY.

Could you please add `DEFECT_UNSURE`, `DEFECT_POTENTIAL`, `DEFECT_INCORRECT`, `DEFECT_FATAL` and `DEFAULT_PATH_ENCODING` to exports?

**Comment by decalage2** [comment]
Also need to add NOSTREAM, as mentioned in https://github.com/decalage2/oletools/issues/204

**Comment by decalage2** [comment]
fixed by commit defd983
