### ISSUE TITLE
Best method to Extract OLE embedded in OLE?

### ISSUE THREAD

**Issue by fligi7** [decalage2/olefile#95]
I'm currently attempting to extract an OLE file (.msg file) embedded within an OLE file (.msg file). More specifically, it is an attachment within one of the attachment streams. 

This stream contains an embedded OLE with streams, starting with the usual...

> [__attach_version1.0_#00000000,__substg1.0_3701000D,__attach_version1.0_#00000000,__properties_version1.0]

... all the way through ...
> [__attach_version1.0_#00000000,__substg1.0_37020102]
[__attach_version1.0_#00000000,__substg1.0_3704001F]
[__attach_version1.0_#00000000,__substg1.0_37090102]
[__attach_version1.0_#00000000,__substg1.0_371D0102]
[__attach_version1.0_#00000000,__substg1.0_3A0C001F]

I see there is a [write_stream](http://olefile.readthedocs.io/en/latest/olefile.html#olefile.OleFileIO.write_stream) function, but I'm uncertain as to how specifically I might use that here to write this set of streams (as a single, complete OLE file) to disk so that I may then iterate over it again as a standalone OLE. 

Would it be as simple as the following?

```
fp = open("message.msg","w") 
write_stream(__attach_version1.0_#00000000, fp)
```
Or am I misinterpreting that function? 

Then again, there is [another example](http://olefile.readthedocs.io/en/latest/olefile.html#olefile.OleFileIO) at the beginning of the docs that lays out the following method that "extracts all image streams from a Microsoft Image Composer file":

```
ole = OleFileIO("fan.mic")

for entry in ole.listdir():
    if entry[1:2] == "Image":
        fin = ole.openstream(entry)
        fout = open(entry[0:1], "wb")
        while True:
            s = fin.read(8192)
            if not s:
                break
            fout.write(s)
```

So, not sure which is the best path forward for my needs here. 

Anything that will help write the attachment as a full standalone OLE file to disk would be much appreciated!

**Comment by decalage2** [comment]
I think the best is to use msg-extractor, which is designed to handle Outlook files: https://github.com/mattgwwalker/msg-extractor - it provides an additional layer on top of olefile.

But if you prefer to use olefile (lower level), then the method to extract data from a stream is openstream (and then read from it): http://olefile.readthedocs.io/en/latest/olefile.html#olefile.OleFileIO.openstream

write_stream is when you want to write data into the OLE file itself. I realize that the names are a bit confusing.

**Comment by fligi7** [comment]
Thanks for the response.

Unfortunately, as is the case with my other unresolved issue [here](https://github.com/decalage2/olefile/issues/91), msg-extractor doesn't provide what I am looking to do. 

I will see what I can do using openstream.

**Comment by fligi7** [comment]
In testing, openstream extracts only the data itself as a file object and not the actual entire stream structure itself, which is what I'd need to write it to an OLE file.

**Comment by decalage2** [comment]
I see. Unfortunately, for the moment olefile can only be used to read OLE files (structure and streams), not to create or write complete OLE files. There is only partial support for modifying existing OLE files, by overwriting data of a stream (see issue #6). So you may find a way to extract the data you are looking for, but currently with olefile, you cannot save the result back to disk as an OLE file.

AFAIK, the only way I know to create an OLE file from scratch using Python, is to use pywin32 on Windows, with the Windows API to create structured storage (pythoncom.StgOpenStorageEx). I never found a proper documentation for that, so in the past I had to look both at the [pywin32 API doc](http://timgolden.me.uk/pywin32-docs/pythoncom__StgOpenStorageEx_meth.html) (very incomplete), [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380342(v=vs.85).aspx) and to search for sample code online. Hope this helps.

**Comment by fligi7** [comment]
Unfortunately, this is being done in Python on Linux so that's a no-go.

Thanks for your help, though. I just wanted to make sure I wasn't missing anything here with your tools that might provide this capability.

**Comment by decalage2** [comment]
well, it looks like some people manage to run python with pywin32 on Linux thanks to WINE: https://superuser.com/questions/328216/install-python-pywin32-in-wine

**Comment by fligi7** [comment]
Agree, and I would be willing to do that on my local system but what I'm currently developing is being run in a more critical environment where the least amount of dependencies (and layers of translators) the better. Appreciate the heads up, though!
