### ISSUE TITLE
olefile > 0.45 - ValueError: write_stream: data must be the same size as the existing stream

### ISSUE THREAD

**Issue by hdm-dt-fb** [decalage2/olefile#99]
First: Thanks a ton for your awesome library!!
Among other places I use it in a small module for accessing data from *.rvt file which are (BIM Revit) model files for virtual buildings:
https://github.com/frederic-beaupere/rvt_detector
Read access works like a charm and I can extract a lot of useful information with the help of olefile.

Now I just read, that with the new olefile version > 0.45 it would be possible to even write differently sized streams back. As this would also massively help for some tasks, I thought I give it a try, following your read-the-docs tutorial:
http://olefile.readthedocs.io/en/latest/Howto.html#overwriting-a-stream
yet olefile complains, that the size of the altered stream does not match. 

Would I need to do something additional to be able to write the stream back?

Here is an excerpt of my REPL session:
```python
import olefile

print(olefile.__version__)
# '0.45.1'

model_path = "D:\\RAC2017\\doc_stair_mod_me.rvt"
rvt_ole = olefile.OleFileIO(model_path, write_mode=True)
tm_data = rvt_ole.openstream('TransmissionData').read()

load_rep = tm_data.replace(b">\x00L\x00o\x00a\x00d\x00e\x00d\x00<", b">\x00U\x00n\x00l\x00o\x00a\x00d\x00e\x00d\x00<")
tm_rep = load_rep.replace(b'T\x00r\x00a\x00n\x00s\x00m\x00i\x00t\x00t\x00e\x00d\x00=\x00"\x00f\x00a\x00l\x00s\x00e\x00"', b'T\x00r\x00a\x00n\x00s\x00m\x00i\x00t\x00t\x00e\x00d\x00=\x00"\x00t\x00r\x00u\x00e\x00"')

print(len(tm_data))
# 3660
print(len(tm_rep))
# 3682

tm_data = rvt_ole.write_stream('TransmissionData', tm_rep)
# File "C:\Program Files\Python36\lib\site-packages\olefile\olefile.py", line 1939, in write_stream
# raise ValueError("write_stream: data must be the same size as the existing stream")
# ValueError: write_stream: data must be the same size as the existing stream
```

**Comment by hdm-dt-fb** [comment]
I forgot to mention, that it works, if the size is the same, but that would mean I would need to have some buffer content in the stream beforehand, in order to adjust after modifications to the same size.

**Comment by decalage2** [comment]
Thanks for the nice words, @hdm-dt-fb. Unfortunately, for 0.45 I just meant olefile can overwrite existing streams of any size (i.e. in the FAT or miniFAT), with data of the *same* size. It cannot change the size of a stream yet. See #6 for more details.

**Comment by hdm-dt-fb** [comment]
Ah I see, thank you for the quick clarification!
Do you have a hint/link by any chance, where 
I could read how to write a larger data stream?
